import json

en = {
  "nav.cores": "Core Pillars",
  "nav.apps": "Ecosystem (18 Apps)",
  "nav.enterprise": "Enterprise",
  "nav.iso": "ISO Standards",
  "nav.gpuCloud": "GPU & Cloud",
  "nav.dao": "DAO & Governance",
  "nav.launchNode": "Launch Node",
  "nav.networkVersion": "Network v1.0",
  "theme.dark": "Dark Mode",
  "theme.light": "Light Mode",
  "theme.auto": "System Theme",
  "hero.badge": "SWAL COMMUNITY RESEARCH LAB 2026",
  "hero.partners": "BELA Colombia & Open Mesh",
  "hero.title1": "Decentralized Memory &",
  "hero.titleGradient": "Sovereign Human AI",
  "hero.title2": "Network.",
  "hero.subtitle": "A community laboratory created to empower humanity by concentrating, preserving, refining, and protecting human collective knowledge with 100% deterministic management and immutable P2P decentralization via Xavier.",
  "hero.exploreApps": "Explore Ecosystem (18 Apps)",
  "hero.enterpriseCase": "Enterprise Portal",
  "hero.telemetryTitle": "Network Telemetry",
  "hero.telemetrySimulated": "[ Simulated Data / Benchmark ]",
  "hero.statNodes": "Target DAO Nodes",
  "hero.statSync": "CRDT P2P Sync",
  "hero.statIso": "Security Ready",
  "cores.badge": "CANONICAL ARCHITECTURE",
  "cores.title": "The 4 Unified",
  "cores.titleAccent": "Core Pillars",
  "cores.subtitle": "The bedrock infrastructure powering every application in the SWAL network. Zero proprietary silos, 100% sovereign deterministic code.",
  "cores.inspectSource": "Inspect Source",
  "cores.xavier.name": "Xavier",
  "cores.xavier.tagline": "Cognitive Agentic Memory Engine",
  "cores.xavier.desc": "Unified high-performance memory daemon in Rust. Combines multi-tier vector indexing, GraphRAG knowledge graphs, and sealed pack verification to ensure agents never lose context across sessions.",
  "cores.xavier.feat1": "L0-L3 Memory Hierarchy",
  "cores.xavier.feat2": "SQLite-vec & Embeddings",
  "cores.xavier.feat3": "GraphRAG Context",
  "cores.xavier.feat4": "XTSP / MCP Server",
  "cores.edgeMesh.name": "edge-mesh",
  "cores.edgeMesh.tagline": "P2P CRDT & Post-Quantum Data Plane",
  "cores.edgeMesh.desc": "Decentralized peer-to-peer transport layer syncing devices without central servers. Implements state-based CRDTs, multi-tenant namespaces, and post-quantum identity (ML-DSA-65 / ML-KEM-768).",
  "cores.edgeMesh.feat1": "State-based CRDT Sync",
  "cores.edgeMesh.feat2": "Quantum-Safe Cryptography",
  "cores.edgeMesh.feat3": "Tor & Onion Routing",
  "cores.edgeMesh.feat4": "Zero Cloud Dependency",
  "cores.agentRunner.name": "swal-agent-runner",
  "cores.agentRunner.tagline": "Autonomous Sandboxed Agent Engine",
  "cores.agentRunner.desc": "Deterministic execution harness for autonomous AI agents. Features complete virtual filesystem (VFS) isolation, capability grants, and GitCore 3.8 parallel task delegation.",
  "cores.agentRunner.feat1": "VFS Sandboxing",
  "cores.agentRunner.feat2": "GitCore 3.8 Protocol",
  "cores.agentRunner.feat3": "WASM Extension Hooks",
  "cores.agentRunner.feat4": "Autonomous Task Waves",
  "cores.swalUi.name": "@swal/ui",
  "cores.swalUi.tagline": "Hive Dark Modular Design System",
  "cores.swalUi.desc": "Canonical design system engineered in Svelte 5 and Tailwind CSS 4. Standardizes visual tokens, accessible cybernetic HUDs, and unified cross-platform interfaces.",
  "cores.swalUi.feat1": "Svelte 5 Runes Native",
  "cores.swalUi.feat2": "Hive Dark Design Tokens",
  "cores.swalUi.feat3": "WCAG AAA Accessibility",
  "cores.swalUi.feat4": "Modular HUD Widgets",
  "apps.badge": "CANONICAL PORTFOLIO",
  "apps.title": "SWAL Ecosystem",
  "apps.titleCount": "(18 Apps)",
  "apps.subtitle": "Explore all live and active decentralized applications. Every app includes complete Pro capabilities out of the box with zero subscriptions.",
  "apps.searchPlaceholder": "Search apps, stack, domain...",
  "apps.allProjects": "All Projects (18)",
  "apps.catEnterprise": "Industrial & Enterprise",
  "apps.catCore": "Core Infrastructure",
  "apps.catCivic": "Civic & Education",
  "apps.catMobile": "Mobile & Wearables",
  "apps.catCreator": "AI & Creator Tools",
  "apps.liveDemo": "Live Demo ↗",
  "apps.publicRepo": "Repository ↗",
  "apps.inviteOnly": "🔒 Invite Only",
  "apps.requestAccess": "Request Access",
  "status.production": "Production",
  "status.active": "Active",
  "status.beta": "Beta",
  "status.published": "Published",
  "app.xavier.tagline": "Cognitive Agentic Memory Engine & GraphRAG",
  "app.xavier.desc": "High-performance persistent memory core in Rust for autonomous AI agents. Multi-tier vector indexing, GraphRAG knowledge graphs, and sealed pack verification.",
  "app.edge-mesh.tagline": "P2P Data Plane & Post-Quantum Network",
  "app.edge-mesh.desc": "Decentralized peer-to-peer data plane with real-time CRDT synchronization, gossip protocol, and post-quantum cryptographic identity (ML-DSA-65 / ML-KEM-768).",
  "app.swal-agent-runner.tagline": "Autonomous Agent Runtime & VFS Sandboxes",
  "app.swal-agent-runner.desc": "Secure, sandboxed execution runtime for local AI agents with virtual filesystem isolation, role-based orchestration, and GitCore 3.8 task execution.",
  "app.swal-ui.tagline": "Unified Hive Dark Design System",
  "app.swal-ui.desc": "Modular, accessible design system engineered in Svelte 5 and Tailwind CSS 4, defining the visual identity and interaction patterns across the SWAL network.",
  "app.worldexams.tagline": "Decentralized Free Educational Testing Platform",
  "app.worldexams.desc": "Academic preparation and testing engine for 16+ countries with automated question generation and local-first AI evaluation.",
  "app.shelf.tagline": "Offline-First POS & Inventory Engine",
  "app.shelf.desc": "Point of sale and inventory management PWA with peer-to-peer CRDT sync. Sell anywhere without internet or expensive proprietary cloud cash registers.",
  "app.orionhealth.tagline": "Privacy-First Health Assistant & SSI",
  "app.orionhealth.desc": "Encrypted personal health ecosystem featuring Self-Sovereign Identity (SSI) on-device, automated sync engines, and offline medical records.",
  "app.isar-memory.tagline": "On-Device Semantic Memory for Dart & Flutter",
  "app.isar-memory.desc": "High-performance vector memory and knowledge graph package published on pub.dev for offline-first Flutter AI applications.",
  "app.swal-files.tagline": "GPU-Accelerated Native Agentic File Manager",
  "app.swal-files.desc": "Ultra-fast file manager in native Rust powered by WGPU hardware rendering and integrated local agent context extraction.",
  "app.pocket-cerebro.tagline": "Offline AI Assistant & Wearables Runtime",
  "app.pocket-cerebro.desc": "Mobile and wearable (WearOS) personal AI assistant running private on-device models with multi-tier memory synchronization.",
  "app.swal-vault.tagline": "Self-Sovereign Identity & Passkey Bóveda",
  "app.swal-vault.desc": "Zero-knowledge biometric passkey wallet and decentralized identity provider integrating with Xavier Clavis.",
  "app.tiktboost.tagline": "Local-First TikTok Studio & AI Analytics",
  "app.tiktboost.desc": "Content scheduling, predictive video engagement metrics, and automated video generation studio running 100% in-browser.",
  "app.maloca.tagline": "Community Governance & Council Assembly Hub",
  "app.maloca.desc": "Universal governance module where humans and autonomous agent delegates deliberate, vote, and manage shared repositories.",
  "app.gos.tagline": "Open Culinary Data & Recipe Interoperability",
  "app.gos.desc": "Open standard and PWA for structured recipe documentation, nutritional analysis, and decentralized restaurant reviews.",
  "app.veedur-ia.tagline": "Civic Intelligence & Public Procurement Audit",
  "app.veedur-ia.desc": "Civic oversight platform for automated anomaly detection, network graphs, and transparency in public contract records (SECOP).",
  "app.nido.tagline": "AI-Assisted Architectural & Space Designer",
  "app.nido.desc": "Interactive architectural layout and interior floor planning tool with WebGPU hardware acceleration and AI layout generation.",
  "app.software-factory.tagline": "Autonomous Multi-Agent CI/CD Engine",
  "app.software-factory.desc": "Automated factory pipeline coordinating Jules, OpenCode, and local agents to deliver verifiable software features.",
  "enterprise.badge": "★ PIONEER COMMERCIAL PARTNER",
  "enterprise.title": "Enterprise Validation:",
  "enterprise.subtitle": "Real-world industrial operations powered by SWAL sovereign local-first architecture in Chile.",
  "enterprise.quote": "SouthWest AI Labs was founded to empower humanity through sovereign local-first technology.",
  "enterprise.description": "SWAL technology enables offline-first industrial operations with zero cloud dependency and complete data sovereignty.",
  "enterprise.accessBtn": "Access App ↗",
  "enterprise.visitPartner": "Visit Portal",
  "enterprise.tableTitle": "Architecture Comparison: Traditional SaaS vs SWAL",
  "enterprise.tableDim": "Dimension",
  "enterprise.tableLegacy": "Traditional Enterprise SaaS",
  "enterprise.tableSwal": "SWAL Sovereign Mesh",
  "enterprise.rowOffline": "Offline Operations",
  "enterprise.rowOfflineLegacy": "Fails or requires clunky sync plugins",
  "enterprise.rowOfflineSwal": "100% Native Local-First (CRDT)",
  "enterprise.rowPrivacy": "Data Privacy",
  "enterprise.rowPrivacyLegacy": "Exfiltrated to US vendor multi-tenant cloud",
  "enterprise.rowPrivacySwal": "Zero-Knowledge on-device persistence",
  "enterprise.rowPricing": "Pricing Model",
  "enterprise.rowPricingLegacy": "$50-$200 / user / month recurring fees",
  "enterprise.rowPricingSwal": "$0 Software fees (Run your own node)",
  "enterprise.rowLockin": "Vendor Lock-In",
  "enterprise.rowLockinLegacy": "Proprietary formats and walled gardens",
  "enterprise.rowLockinSwal": "Open SQLite, AGPL-3.0, Portable",
  "iso.badge": "STANDARDS & CYBERNETIC SECURITY",
  "iso.title": "ISO Compliance &",
  "iso.titleAccent": "Data Governance",
  "iso.subtitle": "Engineered from day one to satisfy rigorous international standards for security, privacy, cloud persistence, and agentic AI oversight.",
  "iso.byDesign": "✔ By-Design Architecture",
  "iso.privateMeshTitle": "Private Mesh & Tor / Onion Transport Layer",
  "iso.privateMeshDesc": "SWAL allows any collective, enterprise, or community to spin up private encrypted P2P mesh networks spanning from 1 to thousands of nodes. Network packets utilize end-to-end ChaCha20-Poly1305 encryption, optional Tor / Onion transport routing, and post-quantum ML-KEM encapsulation, ensuring complete resistance against eavesdropping, ISP tracking, and traffic analysis.",
  "iso.boxMallas": "Private Mallas (1-N)",
  "iso.boxMallasDesc": "Isolated subnets for closed teams",
  "iso.boxTor": "Onion Transport",
  "iso.boxTorDesc": "Tor-hidden routing for peer discovery",
  "iso.boxAcl": "Role-Based ACL",
  "iso.boxAclDesc": "Least-privilege cybernetic access",
  "iso.27001.name": "Information Security Management System (ISMS)",
  "iso.27001.coverage": "100% Control Mapping",
  "iso.27001.desc": "End-to-end cryptographic protection (AES-256-GCM / ML-KEM-768), strict role-based access control (RBAC), and hardware vault isolation.",
  "iso.27001.badge": "Security Base",
  "iso.27701.name": "Privacy Information Management System (PIMS)",
  "iso.27701.coverage": "Local-First Architecture",
  "iso.27701.desc": "Guaranteed zero PII exfiltration. User data is processed on-device and never shared or aggregated without explicit local consent.",
  "iso.27701.badge": "Privacy Sovereign",
  "iso.27017.name": "Cloud Security & PII Protection in Cloud",
  "iso.27017.coverage": "Zero-Knowledge Persistence",
  "iso.27017.desc": "Cloud persistence nodes store only encrypted raw bytes. Storage providers possess zero capability to inspect or parse payload data.",
  "iso.27017.badge": "Cloud Zero-Knowledge",
  "iso.42001.name": "Artificial Intelligence Management System (AIMS)",
  "iso.42001.coverage": "Human-in-the-Loop AI",
  "iso.42001.desc": "Deterministic audit trails for all agentic decisions. AI agents advise and coordinate but never hold unilateral voting authority.",
  "iso.42001.badge": "AI Governance",
  "gpu.badge": "COMPUTE & PERSISTENCE",
  "gpu.title": "Local GPU Inference &",
  "gpu.titleAccent": "Cloud Membership",
  "gpu.subtitle": "Zero software paywalls. Compute runs locally whenever hardware is present. Cloud persistence is billed strictly at direct infrastructure cost.",
  "gpu.localTitle": "Local GPU Acceleration",
  "gpu.localSubtitle": "WebGPU · wgpu · Ollama · llama.cpp",
  "gpu.localBadge": "100% Free & Private",
  "gpu.localDesc": "If your device is equipped with a dedicated or integrated GPU (NVIDIA RTX, Apple Silicon M-series, AMD, Vulkan), SWAL applications run LLM and visual inference locally. Your prompts, embeddings, and context never leave your silicon.",
  "gpu.localCheck1": "Zero latency overhead",
  "gpu.localCheck2": "100% Offline execution",
  "gpu.localCheck3": "Zero API tokens consumed",
  "gpu.cloudTitle": "Partner Cloud Persistence",
  "gpu.cloudSubtitle": "Encrypted Multi-Region Redundancy",
  "gpu.cloudBadge": "Cost-Only Pricing",
  "gpu.cloudDesc": "Optional off-site persistence membership for continuous cloud backup and multi-device sync across continents. Pricing is strictly transparent: you only pay for the raw cloud resources consumed (storage, bandwidth, fallback LLM tokens).",
  "gpu.cloudCheck1": "Zero software markup ($0 license fee)",
  "gpu.cloudCheck2": "End-to-end encrypted storage blobs",
  "gpu.cloudCheck3": "Tiered pricing starting at real VPS cost",
  "dao.badge": "GOVERNANCE ROADMAP",
  "dao.title": "Decentralized Governance &",
  "dao.titleAccent": "Community Handover",
  "dao.subtitle": "Founded by Brahyan Belalcázar as a community research lab. Full protocol governance activates immediately once up to 2 maintainer nodes are operational: SWAL itself as node 1, and any peer node scanned and promoted to maintainer by Xavier.",
  "dao.activeNodes": "Maintainer Nodes (DAO Quorum)",
  "dao.activeNodesReq": "DAO governance operates with up to 2 maintainer nodes: SWAL Genesis (1) + 1 peer promoted by Xavier.",
  "dao.humanNodes": "Peers Scanned by Xavier",
  "dao.humanNodesReq": "Continuous telemetry scanning and health evaluation for promotion to maintainer status.",
  "dao.transparencyTitle": "The Xavier Radical Transparency Commitment",
  "dao.transparencyDesc": "Upon activating the 2-maintainer node quorum, SouthWest AI Labs decentralizes and exposes its institutional memory through Xavier: complete project codebases, architectural decision records (ADRs), full development session histories, agent harnesses, and skill registries — queried immutably across the P2P mesh.",
  "terminal.badge": "INTERACTIVE HUD TERMINAL",
  "terminal.title": "> SWAL_CLI_SIMULATOR",
  "terminal.subtitle": "Test live simulated commands against the Xavier memory core and edge-mesh network.",
  "terminal.placeholder": "Type a command (e.g. swal node status, xavier memory query, help)...",
  "terminal.execute": "Execute",
  "terminal.welcome1": "SWAL Mesh Core v1.0.0-PROD (Linux x86_64)",
  "terminal.welcome2": "Connected to P2P Edge-Mesh via ML-DSA-65 post-quantum transport.",
  "terminal.onlineXavier": "[✓] Xavier Memory Core: ACTIVE (P2P Service)",
  "terminal.onlineStorage": "[✓] Local CRDT Storage: SQLite-vec sync OK",
  "terminal.onlineGpu": "[✓] GPU Acceleration: NVIDIA RTX / WebGPU Active",
  "terminal.onlineIso": "[✓] ISO 27001 Controls: SGSI Active (Encrypted Blobs)",
  "terminal.typeHelp": "Type \"help\" to view available cybernetic commands.",
  "terminal.cmdHelpDesc": "Available Commands:\n  swal node status     - Display local mesh node telemetry\n  xavier memory query  - Inspect cognitive memory vectors\n  mesh peers list      - List connected P2P mesh nodes\n  gpu benchmark        - Run local on-device inference test\n  clear                - Clear terminal screen",
  "terminal.nodeStatusTitle": "--- SWAL LOCAL NODE STATUS ---",
  "terminal.netTopology": "Network Topology: P2P Mesh (Direct + Tor Onion fallback)",
  "terminal.storageLabel": "Storage: 42.8 MB (Local Encrypted SQLite-vec)",
  "terminal.activePeers": "Active Peers: 124 (Chile, Colombia, US, EU)",
  "terminal.karmaScore": "Karma Score: 1,480 points (Soulbound)",
  "terminal.statusHealthy": "Status: HEALTHY (Uptime: 99.98%)",
  "terminal.queryTitle": "--- XAVIER COGNITIVE GRAPH QUERY ---",
  "terminal.queryText": "Query: \"Ecosystem architecture and P2P mesh protocols\"\n[Result 1] apps/shelf (similarity: 0.94) -> Inventory & POS P2P local-first\n[Result 2] cores/edge-mesh (similarity: 0.91) -> CRDT P2P data plane\n[Result 3] cores/xavier/standards (similarity: 0.89) -> ISO compliance & zero paywalls",
  "terminal.peersTitle": "--- CONNECTED P2P PEERS ---\n1. [Chile] node-santiago (Community) -> 12ms\n2. [Colombia] swal-genesis-bela (Core Node) -> 8ms\n3. [Germany] peer-node-berlin (Community) -> 64ms\n4. [Japan] peer-node-tokyo (Community) -> 110ms",
  "terminal.gpuTitle": "--- ON-DEVICE GPU BENCHMARK ---\nDevice: Hardware WebGPU Engine\nInference Engine: Ollama / wgpu Native\nThroughput: 84.6 tokens/sec (Llama-3-8B-Instruct-Q4)\nCloud Tokens Consumed: 0 (Cost: $0.00)",
  "terminal.cmdNotFound": "Error: Command not recognized. Type \"help\" for manual.",
  "footer.desc": "SouthWest AI Labs (SWAL) is an open community deep-tech research lab created to empower humanity by preserving, refining, and decentralizing human collective knowledge using deterministic tools, Xavier, and sovereign P2P networks.",
  "footer.founder": "Founder & Creator: Brahyan Belalcázar (@iberi22 / \"ElBeRi\")",
  "footer.copyright": "© 2026 SouthWest AI Labs (SWAL). AGPL-3.0 / MIT Open Source.",
  "footer.linksTitle": "Ecosystem Links",
  "footer.securityTitle": "Security & Standards"
}

# Translations for 10 languages
es = {
  "nav.cores": "Núcleos Centrales",
  "nav.apps": "Ecosistema (18 Apps)",
  "nav.enterprise": "Empresarial",
  "nav.iso": "Normas ISO",
  "nav.gpuCloud": "GPU y Nube",
  "nav.dao": "DAO y Gobernanza",
  "nav.launchNode": "Iniciar Nodo",
  "nav.networkVersion": "Red v1.0",
  "theme.dark": "Modo Oscuro",
  "theme.light": "Modo Claro",
  "theme.auto": "Tema del Sistema",
  "hero.badge": "LABORATORIO COMUNITARIO SWAL 2026",
  "hero.partners": "BELA Colombia y Red Abierta",
  "hero.title1": "Memoria Descentralizada e",
  "hero.titleGradient": "IA Humana Soberana.",
  "hero.title2": "",
  "hero.subtitle": "Un laboratorio comunitario creado para empoderar a la humanidad concentrando, preservando, afinando y protegiendo el conocimiento colectivo mediante herramientas 100% deterministas y descentralización P2P inmutable vía Xavier.",
  "hero.exploreApps": "Explorar Ecosistema (18 Apps)",
  "hero.enterpriseCase": "Portal Empresarial",
  "hero.telemetryTitle": "Telemetría de Red",
  "hero.telemetrySimulated": "[ Datos Simulados / Benchmark ]",
  "hero.statNodes": "Nodos Objetivo DAO",
  "hero.statSync": "Sincronización CRDT",
  "hero.statIso": "Seguridad ISO",
  "cores.badge": "ARQUITECTURA CANÓNICA",
  "cores.title": "Los 4 Pilares",
  "cores.titleAccent": "Fundacionales",
  "cores.subtitle": "La infraestructura base que alimenta cada aplicación de la red SWAL. Cero silos propietarios, 100% código determinista y soberano.",
  "cores.inspectSource": "Inspeccionar Código",
  "cores.xavier.name": "Xavier",
  "cores.xavier.tagline": "Motor de Memoria Agéntica Cognitiva",
  "cores.xavier.desc": "Demonio de memoria de alto rendimiento unificado en Rust. Combina indexación vectorial multicapa, grafos GraphRAG y paquetes sellados.",
  "cores.xavier.feat1": "Jerarquía de Memoria L0-L3",
  "cores.xavier.feat2": "SQLite-vec y Embeddings",
  "cores.xavier.feat3": "Contexto GraphRAG",
  "cores.xavier.feat4": "Servidor XTSP / MCP",
  "cores.edgeMesh.name": "edge-mesh",
  "cores.edgeMesh.tagline": "Plano de Datos P2P CRDT y Post-Cuántico",
  "cores.edgeMesh.desc": "Capa de transporte P2P descentralizada para sincronizar dispositivos sin servidores centrales. Implementa CRDTs y cifrado post-cuántico.",
  "cores.edgeMesh.feat1": "Sincronización CRDT Nativa",
  "cores.edgeMesh.feat2": "Criptografía Post-Cuántica",
  "cores.edgeMesh.feat3": "Enrutamiento Tor y Onion",
  "cores.edgeMesh.feat4": "Cero Dependencia de Nube",
  "cores.agentRunner.name": "swal-agent-runner",
  "cores.agentRunner.tagline": "Motor de Agentes Autónomos Aislados",
  "cores.agentRunner.desc": "Entorno determinista para agentes de IA autónomos. Incluye aislamiento VFS, permisos y delegación de tareas GitCore 3.8.",
  "cores.agentRunner.feat1": "Aislamiento VFS",
  "cores.agentRunner.feat2": "Protocolo GitCore 3.8",
  "cores.agentRunner.feat3": "Hooks WASM Extensibles",
  "cores.agentRunner.feat4": "Olas de Tareas Autónomas",
  "cores.swalUi.name": "@swal/ui",
  "cores.swalUi.tagline": "Sistema de Diseño Modular Hive Dark",
  "cores.swalUi.desc": "Sistema de diseño canónico creado con Svelte 5 y Tailwind CSS 4. Estandariza tokens visuales e interfaces accesibles.",
  "cores.swalUi.feat1": "Nativo Svelte 5 Runes",
  "cores.swalUi.feat2": "Tokens Hive Dark",
  "cores.swalUi.feat3": "Accesibilidad WCAG AAA",
  "cores.swalUi.feat4": "Componentes HUD Modulares",
  "apps.badge": "PORTAFOLIO CANÓNICO",
  "apps.title": "Ecosistema SWAL",
  "apps.titleCount": "(18 Aplicaciones)",
  "apps.subtitle": "Explora todas las aplicaciones descentralizadas en vivo y activas. Cada aplicación incluye capacidades Pro completas sin suscripciones.",
  "apps.searchPlaceholder": "Buscar apps, stack, dominio...",
  "apps.allProjects": "Todos los Proyectos (18)",
  "apps.catEnterprise": "Industrial y Empresa",
  "apps.catCore": "Infraestructura Núcleo",
  "apps.catCivic": "Cívico y Educación",
  "apps.catMobile": "Móvil y Wearables",
  "apps.catCreator": "IA y Creadores",
  "apps.liveDemo": "Demo en Vivo ↗",
  "apps.publicRepo": "Repositorio ↗",
  "apps.inviteOnly": "🔒 Por Invitación",
  "apps.requestAccess": "Solicitar Acceso",
  "status.production": "Producción",
  "status.active": "Activo",
  "status.beta": "Beta",
  "status.published": "Publicado",
  "app.xavier.tagline": "Motor de Memoria Agéntica Cognitiva y GraphRAG",
  "app.xavier.desc": "Núcleo de memoria persistente de alto rendimiento en Rust para agentes autónomos. Indexación vectorial, grafos de conocimiento e inspección inmutable.",
  "app.edge-mesh.tagline": "Plano de Datos P2P y Red Post-Cuántica",
  "app.edge-mesh.desc": "Red P2P descentralizada con sincronización CRDT en tiempo real, protocolo gossip e identidad criptográfica post-cuántica.",
  "app.swal-agent-runner.tagline": "Ejecutor de Agentes y Sandbox VFS",
  "app.swal-agent-runner.desc": "Runtime seguro y aislado para agentes de IA locales con sistema de archivos virtual y delegación GitCore 3.8.",
  "app.swal-ui.tagline": "Sistema de Diseño Unificado Hive Dark",
  "app.swal-ui.desc": "Sistema de diseño modular creado con Svelte 5 y Tailwind CSS 4 que define la identidad visual de la red SWAL.",
  "app.worldexams.tagline": "Plataforma Educativa Gratuita Descentralizada",
  "app.worldexams.desc": "Motor de preparación académica y exámenes para más de 16 países con generación automatizada de preguntas e IA local.",
  "app.shelf.tagline": "Punto de Venta e Inventario Local-First",
  "app.shelf.desc": "PWA de punto de venta e inventarios con sincronización CRDT P2P. Vende en cualquier lugar sin internet ni cajas registradoras costosas.",
  "app.orionhealth.tagline": "Asistente de Salud Privado con Identidad SSI",
  "app.orionhealth.desc": "Ecosistema de salud personal cifrado con Identidad Soberana (SSI), motores de sync automatizados y registros médicos offline.",
  "app.isar-memory.tagline": "Memoria Semántica en Dispositivo para Dart y Flutter",
  "app.isar-memory.desc": "Paquete de memoria vectorial y grafos en pub.dev para aplicaciones de IA en Flutter offline-first.",
  "app.swal-files.tagline": "Gestor de Archivos Nativo Acelerado por GPU",
  "app.swal-files.desc": "Gestor de archivos ultrarrápido en Rust impulsado por renderizado hardware WGPU y extracción de contexto local.",
  "app.pocket-cerebro.tagline": "Asistente de IA Offline y Runtime para Wearables",
  "app.pocket-cerebro.desc": "Asistente móvil y wearable (WearOS) que ejecuta modelos privados en el dispositivo con sincronización multicapa.",
  "app.swal-vault.tagline": "Bóveda de Identidad Soberana y Passkeys",
  "app.swal-vault.desc": "Billetera biométrica de passkeys Zero-Knowledge y proveedor de identidad descentralizado integrado con Xavier Clavis.",
  "app.tiktboost.tagline": "Estudio TikTok Local-First y Analítica IA",
  "app.tiktboost.desc": "Programación de contenidos, métricas predictivas de interacción y estudio automatizado de video 100% en el navegador.",
  "app.maloca.tagline": "Hub de Gobernanza Comunitaria y Asamblea",
  "app.maloca.desc": "Módulo de gobernanza universal donde humanos y agentes delegados deliberan, votan y gestionan repositorios compartidos.",
  "app.gos.tagline": "Estándar Gastronómico Abierto e Interoperabilidad",
  "app.gos.desc": "Estándar abierto y PWA para documentación de recetas, análisis nutricional y reseñas descentralizadas.",
  "app.veedur-ia.tagline": "Inteligencia Cívica y Auditoría de Compras Públicas",
  "app.veedur-ia.desc": "Plataforma de veeduría cívica para detección de anomalías y transparencia en contratos públicos (SECOP).",
  "app.nido.tagline": "Diseñador Arquitectónico Assistido por IA",
  "app.nido.desc": "Herramienta interactiva de diseño arquitectónico con aceleración WebGPU y generación inteligente de espacios.",
  "app.software-factory.tagline": "Motor CI/CD Autónomo Multi-Agente",
  "app.software-factory.desc": "Fábrica automatizada de software coordinando agentes Jules, OpenCode y locales para entregar características verificables.",
  "enterprise.badge": "★ SOCIO COMERCIAL PIONERO",
  "enterprise.title": "Validación Empresarial:",
  "enterprise.subtitle": "Operaciones industriales reales potenciadas por la arquitectura soberana local-first de SWAL en Chile.",
  "enterprise.quote": "SouthWest AI Labs fue fundado para empoderar a la humanidad a través de tecnología soberana local-first.",
  "enterprise.description": "La tecnología SWAL permite operaciones industriales offline-first con cero dependencia de la nube y soberanía completa de datos.",
  "enterprise.accessBtn": "Acceder a App ↗",
  "enterprise.visitPartner": "Visitar Portal",
  "enterprise.tableTitle": "Comparativa de Arquitectura: SaaS Tradicional vs SWAL",
  "enterprise.tableDim": "Dimensión",
  "enterprise.tableLegacy": "SaaS Empresarial Tradicional",
  "enterprise.tableSwal": "Malla Soberana SWAL",
  "enterprise.rowOffline": "Operación Offline",
  "enterprise.rowOfflineLegacy": "Falla o requiere plugins complejos",
  "enterprise.rowOfflineSwal": "100% Nativo Local-First (CRDT)",
  "enterprise.rowPrivacy": "Privacidad de Datos",
  "enterprise.rowPrivacyLegacy": "Exfiltrados a nube multi-tenant de terceros",
  "enterprise.rowPrivacySwal": "Persistencia en dispositivo Zero-Knowledge",
  "enterprise.rowPricing": "Modelo de Precios",
  "enterprise.rowPricingLegacy": "$50-$200 / usuario / mes recurrente",
  "enterprise.rowPricingSwal": "$0 Coste de software (Opera tu propio nodo)",
  "enterprise.rowLockin": "Bloqueo de Proveedor",
  "enterprise.rowLockinLegacy": "Formatos propietarios y jardines amurallados",
  "enterprise.rowLockinSwal": "SQLite Abierto, AGPL-3.0, Portable",
  "iso.badge": "ESTÁNDARES Y CIBERSEGURIDAD",
  "iso.title": "Cumplimiento ISO y",
  "iso.titleAccent": "Gobernanza de Datos",
  "iso.subtitle": "Diseñado desde el día uno para satisfacer rigurosos estándares internacionales de seguridad, privacidad, persistencia cloud y supervisión de IA.",
  "iso.byDesign": "✔ Arquitectura por Diseño",
  "iso.privateMeshTitle": "Malla Privada y Capa de Transporte Tor / Onion",
  "iso.privateMeshDesc": "SWAL permite a cualquier colectivo, empresa o comunidad desplegar redes malladas P2P privadas de 1 a miles de nodos con cifrado ChaCha20-Poly1305 y transporte Tor.",
  "iso.boxMallas": "Mallas Privadas (1-N)",
  "iso.boxMallasDesc": "Subredes aisladas para equipos cerrados",
  "iso.boxTor": "Transporte Onion",
  "iso.boxTorDesc": "Enrutamiento Tor para descubrimiento de pares",
  "iso.boxAcl": "ACL por Roles",
  "iso.boxAclDesc": "Acceso cibernético de mínimo privilegio",
  "iso.27001.name": "Sistema de Gestión de Seguridad (SGSI)",
  "iso.27001.coverage": "100% Cobertura de Controles",
  "iso.27001.desc": "Protección criptográfica punta a punta (AES-256 / ML-KEM), control RBAC y aislamiento en hardware vault.",
  "iso.27001.badge": "Base de Seguridad",
  "iso.27701.name": "Sistema de Gestión de Privacidad (PIMS)",
  "iso.27701.coverage": "Arquitectura Local-First",
  "iso.27701.desc": "Cero exfiltración de PII. Procesamiento local en dispositivo sin agregar datos sin consentimiento.",
  "iso.27701.badge": "Soberanía de Privacidad",
  "iso.27017.name": "Seguridad Cloud y Protección PII",
  "iso.27017.coverage": "Persistencia Zero-Knowledge",
  "iso.27017.desc": "Los nodos cloud almacenan solo bytes cifrados sin capacidad de inspección o lectura.",
  "iso.27017.badge": "Nube Zero-Knowledge",
  "iso.42001.name": "Sistema de Gestión de IA (AIMS)",
  "iso.42001.coverage": "IA con Control Humano",
  "iso.42001.desc": "Trazabilidad determinista para cada decisión agéntica. La IA asesora pero nunca vota de forma unilateral.",
  "iso.42001.badge": "Gobernanza de IA",
  "gpu.badge": "CÓMPUTO Y PERSISTENCIA",
  "gpu.title": "Inferencia Local por GPU y",
  "gpu.titleAccent": "Membresía Cloud",
  "gpu.subtitle": "Cero muros de pago de software. El cómputo corre localmente cuando hay hardware disponible. La persistencia en nube se cobra a coste directo de servidor.",
  "gpu.localTitle": "Aceleración Local por GPU",
  "gpu.localSubtitle": "WebGPU · wgpu · Ollama · llama.cpp",
  "gpu.localBadge": "100% Gratis y Privado",
  "gpu.localDesc": "Si tu dispositivo cuenta con GPU dedicada o integrada (NVIDIA RTX, Apple Silicon serie M, AMD, Vulkan), SWAL ejecuta inferencia de LLM y visión en local.",
  "gpu.localCheck1": "Cero latencia de red",
  "gpu.localCheck2": "100% Ejecución offline",
  "gpu.localCheck3": "Cero tokens de API consumidos",
  "gpu.cloudTitle": "Persistencia en Nube de Socio",
  "gpu.cloudSubtitle": "Redundancia Multirregión Cifrada",
  "gpu.cloudBadge": "Precio a Coste Real",
  "gpu.cloudDesc": "Membresía opcional de respaldo para sincronización continua y copia de seguridad en la nube a precio transparente.",
  "gpu.cloudCheck1": "Cero margen sobre el software ($0 licencia)",
  "gpu.cloudCheck2": "Blobs de almacenamiento cifrados E2E",
  "gpu.cloudCheck3": "Precios por niveles basados en coste VPS",
  "dao.badge": "HOJA DE RUTA DE GOBERNANZA",
  "dao.title": "Gobernanza Descentralizada y",
  "dao.titleAccent": "Traspaso a la Comunidad",
  "dao.subtitle": "Fundado por Brahyan Belalcázar como un laboratorio comunitario. La gobernanza DAO funciona apenas existan hasta 2 nodos mantenedores: SWAL mismo como nodo 1 y cualquier otro nodo que Xavier escanee y promueva a nodo mantenedor.",
  "dao.activeNodes": "Nodos Mantenedores (Quórum DAO)",
  "dao.activeNodesReq": "La gobernanza DAO opera con hasta 2 nodos mantenedores: SWAL Génesis (1) + 1 nodo promovido por Xavier.",
  "dao.humanNodes": "Nodos Evaluados por Xavier",
  "dao.humanNodesReq": "Escaneo continuo de telemetría y salud para elegibilidad y promoción a mantenedor.",
  "dao.transparencyTitle": "El Compromiso de Transparencia Radical de Xavier",
  "dao.transparencyDesc": "Al activar el quórum de 2 nodos mantenedores, SWAL descentralizará y expondrá su memoria institucional a través de Xavier: código, ADRs, historiales de desarrollo y registros agénticos.",
  "terminal.badge": "TERMINAL HUD INTERACTIVO",
  "terminal.title": "> SIMULADOR_CLI_SWAL",
  "terminal.subtitle": "Prueba comandos simulados en vivo contra el núcleo de memoria Xavier y la red edge-mesh.",
  "terminal.placeholder": "Escribe un comando (ej. swal node status, xavier memory query, help)...",
  "terminal.execute": "Ejecutar",
  "terminal.welcome1": "Núcleo SWAL Mesh v1.0.0-PROD (Linux x86_64)",
  "terminal.welcome2": "Conectado a P2P Edge-Mesh vía transporte post-cuántico ML-DSA-65.",
  "terminal.onlineXavier": "[✓] Núcleo de Memoria Xavier: ACTIVO (Servicio P2P)",
  "terminal.onlineStorage": "[✓] Almacenamiento CRDT Local: Sync SQLite-vec OK",
  "terminal.onlineGpu": "[✓] Aceleración GPU: NVIDIA RTX / WebGPU Activo",
  "terminal.onlineIso": "[✓] Controles ISO 27001: SGSI Activo (Blobs Cifrados)",
  "terminal.typeHelp": "Escribe \"help\" para ver la lista de comandos disponibles.",
  "terminal.cmdHelpDesc": "Comandos Disponibles:\n  swal node status     - Muestra la telemetría del nodo local\n  xavier memory query  - Inspecciona los vectores de memoria cognitiva\n  mesh peers list      - Lista los nodos P2P conectados\n  gpu benchmark        - Ejecuta prueba de inferencia local por GPU\n  clear                - Limpia la pantalla de la terminal",
  "terminal.nodeStatusTitle": "--- ESTADO DEL NODO LOCAL SWAL ---",
  "terminal.netTopology": "Topología de Red: P2P Mesh (Directo + Red Tor Onion)",
  "terminal.storageLabel": "Almacenamiento: 42.8 MB (SQLite-vec Cifrado Local)",
  "terminal.activePeers": "Pares Activos: 124 (Chile, Colombia, EE.UU., UE)",
  "terminal.karmaScore": "Puntaje Karma: 1,480 puntos (Vinculado al Alma)",
  "terminal.statusHealthy": "Estado: SALUDABLE (Disponibilidad: 99.98%)",
  "terminal.queryTitle": "--- CONSULTA GRAFO COGNITIVO XAVIER ---",
  "terminal.queryText": "Consulta: \"Arquitectura de ecosistema y protocolos P2P\"\n[Resultado 1] apps/shelf (similitud: 0.94) -> Inventario y POS P2P local-first\n[Resultado 2] cores/edge-mesh (similitud: 0.91) -> Plano de datos CRDT P2P\n[Resultado 3] cores/xavier/standards (similitud: 0.89) -> Cumplimiento ISO y cero pagos",
  "terminal.peersTitle": "--- PARES P2P CONECTADOS ---\n1. [Chile] node-santiago (Comunidad) -> 12ms\n2. [Colombia] swal-genesis-bela (Nodo Núcleo) -> 8ms\n3. [Alemania] peer-node-berlin (Comunidad) -> 64ms\n4. [Japón] peer-node-tokyo (Comunidad) -> 110ms",
  "terminal.gpuTitle": "--- BENCHMARK GPU EN DISPOSITIVO ---\nDispositivo: Motor Hardware WebGPU\nMotor de Inferencia: Ollama / wgpu Nativo\nRendimiento: 84.6 tokens/seg (Llama-3-8B-Instruct-Q4)\nTokens de Nube Consumidos: 0 (Coste: $0.00)",
  "terminal.cmdNotFound": "Error: Comando no reconocido. Escribe \"help\" para ayuda.",
  "footer.desc": "SouthWest AI Labs (SWAL) es un laboratorio comunitario de investigación deep-tech creado para empoderar a la humanidad preservando, afinando y descentralizando el conocimiento colectivo.",
  "footer.founder": "Fundador y Creador: Brahyan Belalcázar (@iberi22 / \"ElBeRi\")",
  "footer.copyright": "© 2026 SouthWest AI Labs (SWAL). Código Abierto AGPL-3.0 / MIT.",
  "footer.linksTitle": "Enlaces del Ecosistema",
  "footer.securityTitle": "Seguridad y Estándares"
}

# Copy base keys for other languages and translate key terms
def create_locale(lang_code, lang_name, overrides):
    d = dict(en)
    for k, v in overrides.items():
        d[k] = v
    return d

zh = create_locale("zh", "Chinese", {
  "nav.cores": "核心支柱",
  "nav.apps": "生态系统 (18个应用)",
  "nav.enterprise": "企业级验证",
  "nav.iso": "ISO ISO标准",
  "nav.gpuCloud": "GPU 与云端",
  "nav.dao": "DAO 与治理",
  "nav.launchNode": "启动节点",
  "nav.networkVersion": "网络 v1.0",
  "theme.dark": "深色模式",
  "theme.light": "浅色模式",
  "theme.auto": "跟随系统",
  "hero.badge": "SWAL 社区实验室 2026",
  "hero.partners": "BELA 哥伦比亚 & 开放网络",
  "hero.title1": "去中心化记忆与",
  "hero.titleGradient": "主权人类人工智能",
  "hero.title2": "网络。",
  "hero.subtitle": "一个旨在通过 Xavier 实现100%确定性管理和不可篡改的P2P去中心化，集中、保存、精炼和保护人类集体知识的社区实验室。",
  "hero.exploreApps": "探索生态系统 (18个应用)",
  "hero.enterpriseCase": "企业门户",
  "hero.telemetryTitle": "网络遥测",
  "hero.telemetrySimulated": "[ 模拟数据 / 基准测试 ]",
  "hero.statNodes": "目标 DAO 节点",
  "hero.statSync": "CRDT P2P 同步",
  "hero.statIso": "安全就绪",
  "cores.badge": "典范架构",
  "cores.title": "四大统一",
  "cores.titleAccent": "核心支柱",
  "cores.subtitle": "驱动 SWAL 网络中每个应用的底层基础设施。零专有壁垒，100% 主权确定性代码。",
  "cores.inspectSource": "查看源码",
  "cores.xavier.tagline": "认知智能体记忆引擎",
  "cores.edgeMesh.tagline": "P2P CRDT 与后量子数据平面",
  "cores.agentRunner.tagline": "自主沙盒智能体引擎",
  "cores.swalUi.tagline": "Hive Dark 模块化设计系统",
  "apps.badge": "典范组合",
  "apps.title": "SWAL 生态系统",
  "apps.titleCount": "(18个应用)",
  "apps.subtitle": "探索所有在线活力的去中心化应用。开箱即用，包含全部 Pro 功能，零订阅费用。",
  "apps.searchPlaceholder": "搜索应用、技术栈、领域...",
  "apps.allProjects": "所有项目 (18)",
  "apps.catEnterprise": "工业与企业",
  "apps.catCore": "核心基础设施",
  "apps.catCivic": "公民与教育",
  "apps.catMobile": "移动与穿戴设备",
  "apps.catCreator": "AI 与创作者工具",
  "apps.liveDemo": "在线演示 ↗",
  "apps.publicRepo": "代码仓库 ↗",
  "apps.inviteOnly": "🔒 仅限邀请",
  "apps.requestAccess": "申请访问",
  "status.production": "生产环境",
  "status.active": "活跃",
  "status.beta": "测试版",
  "status.published": "已发布",
  "iso.badge": "标准与网络安全",
  "iso.title": "ISO 合规与",
  "iso.titleAccent": "数据治理",
  "iso.subtitle": "从第一天起就为满足严格的安全、隐私、云持久性和AI监管国际标准而设计。",
  "iso.byDesign": "✔ 原生设计架构",
  "gpu.badge": "计算与持久化",
  "gpu.title": "本地 GPU 推理与",
  "gpu.titleAccent": "云端会员",
  "gpu.subtitle": "零软件付费墙。有硬件时在本地运行计算。云端持久化仅按直接基础设施成本计费。",
  "dao.badge": "治理路线图",
  "dao.title": "去中心化治理与",
  "dao.titleAccent": "社区移交",
  "dao.subtitle": "由 Brahyan Belalcázar 创建的社区实验室。达到可验证网络规模后，完整协议治理权将正式移交给社区 DAO。",
  "terminal.badge": "交互式 HUD 终端",
  "terminal.title": "> SWAL_CLI_模拟器",
  "terminal.subtitle": "针对 Xavier 记忆核心和边缘网状网络测试实时模拟命令。",
  "terminal.placeholder": "输入命令 (例如 swal node status, xavier memory query, help)...",
  "terminal.execute": "执行",
  "footer.desc": "SouthWest AI Labs (SWAL) 是一个开放社区深科技实验室，旨在通过确定性工具、Xavier 和主权 P2P 网络保存、精炼和去中心化人类集体知识。",
  "footer.founder": "创始人与缔造者: Brahyan Belalcázar (@iberi22 / \"ElBeRi\")",
  "footer.copyright": "© 2026 SouthWest AI Labs (SWAL). AGPL-3.0 / MIT 开源协议。",
  "footer.linksTitle": "生态系统链接",
  "footer.securityTitle": "安全与标准"
})

hi = create_locale("hi", "Hindi", {
  "nav.cores": "मुख्य स्तंभ",
  "nav.apps": "पारिस्थितिकी तंत्र (18 ऐप्स)",
  "nav.enterprise": "उद्यम (Enterprise)",
  "nav.iso": "आईएसओ मानक",
  "nav.gpuCloud": "जीपीयू और क्लाउड",
  "nav.dao": "डीएओ और शासन",
  "nav.launchNode": "नोड शुरू करें",
  "nav.networkVersion": "नेटवर्क v1.0",
  "theme.dark": "डार्क मोड",
  "theme.light": "लाइट मोड",
  "theme.auto": "सिस्टम थीम",
  "hero.badge": "SWAL समुदाय अनुसंधान लैब 2026",
  "hero.partners": "BELA कोलंबिया और ओपन मेश",
  "hero.title1": "विकेंद्रीकृत स्मृति और",
  "hero.titleGradient": "संप्रभु मानव एआई",
  "hero.title2": "नेटवर्क।",
  "hero.subtitle": "Xavier के माध्यम से 100% निश्चयात्मक प्रबंधन और अपरिवर्तनीय P2P विकेंद्रीकरण के साथ मानव सामूहिक ज्ञान को केंद्रित, संरक्षित, परिष्कृत और सुरक्षित करने के लिए निर्मित एक सामुदायिक प्रयोगशाला।",
  "hero.exploreApps": "पारिस्थितिकी तंत्र देखें (18 ऐप्स)",
  "hero.enterpriseCase": "एंटरप्राइज पोर्टल",
  "hero.telemetryTitle": "नेटवर्क टेलीमेट्री",
  "hero.telemetrySimulated": "[ सिमुलेटेड डेटा / बेंचमार्क ]",
  "hero.statNodes": "लक्ष्य डीएओ नोड्स",
  "hero.statSync": "CRDT P2P सिंक",
  "hero.statIso": "सुरक्षा तैयार",
  "cores.badge": "प्रामाणिक वास्तुकला",
  "cores.title": "4 एकीकृत",
  "cores.titleAccent": "मुख्य स्तंभ",
  "cores.subtitle": "SWAL नेटवर्क में हर एप्लिकेशन को सशक्त बनाने वाला बुनियादी ढांचा। शून्य स्वामित्व साइलो, 100% संप्रभु कोड।",
  "cores.inspectSource": "सोर्स कोड देखें",
  "apps.badge": "प्रामाणिक पोर्टफोलियो",
  "apps.title": "SWAL पारिस्थितिकी तंत्र",
  "apps.titleCount": "(18 ऐप्स)",
  "apps.subtitle": "सभी लाइव और सक्रिय विकेंद्रीकृत एप्लिकेशनों का अन्वेषण करें। हर ऐप में शून्य सदस्यता के साथ प्रो सुविधाएं शामिल हैं।",
  "apps.searchPlaceholder": "ऐप्स, स्टैक, डोमेन खोजें...",
  "apps.allProjects": "सभी प्रोजेक्ट्स (18)",
  "apps.catEnterprise": "औद्योगिक और उद्यम",
  "apps.catCore": "मूल अवसंरचना",
  "apps.catCivic": "नागरिक और शिक्षा",
  "apps.catMobile": "मोबाइल और वियरेबल्स",
  "apps.catCreator": "एआई और क्रिएटर टूल",
  "apps.liveDemo": "लाइव डेमो ↗",
  "apps.publicRepo": "रिपॉजिटरी ↗",
  "apps.inviteOnly": "🔒 केवल निमंत्रण",
  "apps.requestAccess": "पहुंच का अनुरोध करें",
  "status.production": "उत्पादन",
  "status.active": "सक्रिय",
  "status.beta": "बीटा",
  "status.published": "प्रकाशित",
  "iso.badge": "मानक और साइबर सुरक्षा",
  "iso.title": "आईएसओ अनुपालन और",
  "iso.titleAccent": "डेटा गवर्नेंस",
  "gpu.badge": "गणना और दृढ़ता",
  "gpu.title": "स्थानीय जीपीयू अनुमान और",
  "gpu.titleAccent": "क्लाउड सदस्यता",
  "dao.badge": "शासन का रोडमैप",
  "dao.title": "विकेंद्रीकृत शासन और",
  "dao.titleAccent": "समुदाय को हस्तांतरण",
  "terminal.badge": "इंटरएक्टिव HUD टर्मिनल",
  "terminal.title": "> SWAL_CLI_सिम्युलेटर",
  "terminal.subtitle": "Xavier मेमोरी कोर और मेश नेटवर्क के खिलाफ कमांड्स का परीक्षण करें।",
  "terminal.placeholder": "एक कमांड टाइप करें (जैसे swal node status, xavier memory query, help)...",
  "terminal.execute": "निष्पादित करें",
  "footer.desc": "SouthWest AI Labs (SWAL) एक खुला समुदाय अनुसंधान लैब है जिसे मानव ज्ञान को संरक्षित और विकेंद्रीकृत करने के लिए बनाया गया है।",
  "footer.founder": "संस्थापक और निर्माता: Brahyan Belalcázar (@iberi22 / \"ElBeRi\")",
  "footer.copyright": "© 2026 SouthWest AI Labs (SWAL). AGPL-3.0 / MIT ओपन सोर्स।",
  "footer.linksTitle": "इकोसिस्टम लिंक्स",
  "footer.securityTitle": "सुरक्षा और मानक"
})

ar = create_locale("ar", "Arabic", {
  "nav.cores": "الأركان الأساسية",
  "nav.apps": "النظام البيئي (18 تطبيقًا)",
  "nav.enterprise": "المؤسسات",
  "nav.iso": "معايير ISO",
  "nav.gpuCloud": "GPU والسحابة",
  "nav.dao": "DAO والحوكمة",
  "nav.launchNode": "تشغيل عقدة",
  "nav.networkVersion": "الشبكة الإصدار 1.0",
  "theme.dark": "الوضع الداكن",
  "theme.light": "الوضع الفاتح",
  "theme.auto": "نمط النظام",
  "hero.badge": "مختبر أبحاث مجتمع SWAL 2026",
  "hero.partners": "BELA كولومبيا والشبكة المفتوحة",
  "hero.title1": "ذاكرة غير مركزية و",
  "hero.titleGradient": "ذكاء اصطناعي بشري سيادي",
  "hero.title2": "شبكة.",
  "hero.subtitle": "مختبر مجتمعي تم إنشاؤه لتمكين البشرية من خلال تركيز وحفظ وصقل وحماية المعرفة الجماعية البشرية مع إدارة حتمية بنسبة 100٪ وعدم مركزية P2P غير قابلة للتغيير عبر Xavier.",
  "hero.exploreApps": "استكشاف النظام البيئي (18 تطبيقًا)",
  "hero.enterpriseCase": "بوابة المؤسسات",
  "hero.telemetryTitle": "قياسات الشبكة",
  "hero.telemetrySimulated": "[ بيانات محاكاة / اختبار ]",
  "hero.statNodes": "عقد DAO المستهدفة",
  "hero.statSync": "مزامنة CRDT P2P",
  "hero.statIso": "جاهز للأمان ISO",
  "cores.badge": "الهندسة المعمارية القياسية",
  "cores.title": "الأركان الأربعة",
  "cores.titleAccent": "الموحدة",
  "cores.subtitle": "البنية التحتية الأساسية التي تشغل كل تطبيق في شبكة SWAL. صفر صوامع مملوكة، 100٪ كود سيادي حتمي.",
  "cores.inspectSource": "فحص المصدر",
  "apps.badge": "المحفظة القياسية",
  "apps.title": "نظام SWAL البيئي",
  "apps.titleCount": "(18 تطبيقًا)",
  "apps.subtitle": "استكشف جميع التطبيقات اللامركزية النشطة. يتضمن كل تطبيق ميزات Pro كاملة دون أي اشتراكات.",
  "apps.searchPlaceholder": "البحث في التطبيقات، التقنيات...",
  "apps.allProjects": "جميع المشاريع (18)",
  "apps.catEnterprise": "الصناعة والمؤسسات",
  "apps.catCore": "البنية التحتية الأساسية",
  "apps.catCivic": "التعليم والمدني",
  "apps.catMobile": "الهواتف والأجهزة الملبوسة",
  "apps.catCreator": "أدوات الذكاء الاصطناعي والمبدعين",
  "apps.liveDemo": "عرض حي ↗",
  "apps.publicRepo": "المستودع ↗",
  "apps.inviteOnly": "🔒 بدعوة فقط",
  "apps.requestAccess": "طلب وصول",
  "status.production": "إنتاج",
  "status.active": "نشط",
  "status.beta": "تجريبي",
  "status.published": "منشور",
  "iso.badge": "المعايير والأمن السيبراني",
  "iso.title": "الامتثال لمعايير ISO و",
  "iso.titleAccent": "حوكمة البيانات",
  "iso.subtitle": "مصمم منذ اليوم الأول لتلبية المعايير الدولية الصارمة للأمن والخصوصية والاستمرارية السحابية.",
  "iso.byDesign": "✔ هندسة معمارية بالتصميم",
  "gpu.badge": "الحوسبة والاستمرارية",
  "gpu.title": "استنتاج GPU المحلي و",
  "gpu.titleAccent": "عضوية السحابة",
  "gpu.subtitle": "لا توجد جدران دفع برمجية. يتم تشغيل الحوسبة محليًا عند توفر الأجهزة.",
  "dao.badge": "خارطة طريق الحوكمة",
  "dao.title": "الحوكمة اللامركزية و",
  "dao.titleAccent": "تسليم المجتمع",
  "dao.subtitle": "تأسس بواسطة Brahyan Belalcázar كمختبر أبحاث مجتمعي. سيتم نقل حوكمة البروتوكول بالكامل إلى DAO المجتمع.",
  "terminal.badge": "طرفية HUD التفاعلية",
  "terminal.title": "> محاكي_SWAL_CLI",
  "terminal.subtitle": "اختبار الأوامر المحاكاة الحية ضد نواة ذاكرة Xavier وشبكة edge-mesh.",
  "terminal.placeholder": "اكتب أمرًا (مثل swal node status, xavier memory query, help)...",
  "terminal.execute": "تشغيل",
  "footer.desc": "SouthWest AI Labs (SWAL) هو مختبر أبحاث تقني مجتمعي مفتوح لتمكين البشرية عبر حفظ المعرفة الجماعية وتوزيعها.",
  "footer.founder": "المؤسس والمبتكر: Brahyan Belalcázar (@iberi22 / \"ElBeRi\")",
  "footer.copyright": "© 2026 SouthWest AI Labs (SWAL). مفتوح المصدر AGPL-3.0 / MIT.",
  "footer.linksTitle": "روابط النظام البيئي",
  "footer.securityTitle": "الأمان والمعايير"
})

fr = create_locale("fr", "French", {
  "nav.cores": "Piliers Centraux",
  "nav.apps": "Écosystème (18 Apps)",
  "nav.enterprise": "Entreprise",
  "nav.iso": "Normes ISO",
  "nav.gpuCloud": "GPU & Nuage",
  "nav.dao": "DAO & Gouvernance",
  "nav.launchNode": "Lancer un Nœud",
  "nav.networkVersion": "Réseau v1.0",
  "theme.dark": "Mode Sombre",
  "theme.light": "Mode Clair",
  "theme.auto": "Thème Système",
  "hero.badge": "LABORATOIRE DE RECHERCHE COMMUNAUTAIRE SWAL 2026",
  "hero.partners": "BELA Colombie & Réseau Ouvert",
  "hero.title1": "Mémoire Décentralisée &",
  "hero.titleGradient": "IA Humaine Souveraine",
  "hero.title2": "Réseau.",
  "hero.subtitle": "Un laboratoire communautaire créé pour autonomiser l'humanité en concentrant, préservant, affinant et protégeant le savoir collectif humain avec une gestion 100% déterministe et une décentralisation P2P via Xavier.",
  "hero.exploreApps": "Explorer l'Écosystème (18 Apps)",
  "hero.enterpriseCase": "Portail Entreprise",
  "hero.telemetryTitle": "Télémétrie Réseau",
  "hero.telemetrySimulated": "[ Données Simulées / Benchmark ]",
  "hero.statNodes": "Nœuds DAO Cibles",
  "hero.statSync": "Synchro CRDT P2P",
  "hero.statIso": "Sécurité Conforme ISO",
  "cores.badge": "ARCHITECTURE CANONIQUE",
  "cores.title": "Les 4 Piliers",
  "cores.titleAccent": "Fondateurs",
  "cores.subtitle": "L'infrastructure de base alimentant chaque application du réseau SWAL. Zéro silo propriétaire, 100% code souverain déterministe.",
  "cores.inspectSource": "Inspecter le Code",
  "apps.badge": "PORTFOLIO CANONIQUE",
  "apps.title": "Écosystème SWAL",
  "apps.titleCount": "(18 Apps)",
  "apps.subtitle": "Explorez toutes les applications décentralisées actives. Chaque application inclut des fonctionnalités Pro complètes sans aucun abonnement.",
  "apps.searchPlaceholder": "Rechercher des apps, stacks, domaines...",
  "apps.allProjects": "Tous les Projets (18)",
  "apps.catEnterprise": "Industriel & Entreprise",
  "apps.catCore": "Infrastructure de Base",
  "apps.catCivic": "Civique & Éducation",
  "apps.catMobile": "Mobile & Wearables",
  "apps.catCreator": "Outils IA & Créateurs",
  "apps.liveDemo": "Démo en Direct ↗",
  "apps.publicRepo": "Dépôt ↗",
  "apps.inviteOnly": "🔒 Sur Invitation",
  "apps.requestAccess": "Demander l'Accès",
  "status.production": "Production",
  "status.active": "Actif",
  "status.beta": "Bêta",
  "status.published": "Publié",
  "iso.badge": "NORMES ET CYBERSÉCURITÉ",
  "iso.title": "Conformité ISO &",
  "iso.titleAccent": "Gouvernance des Données",
  "iso.subtitle": "Conçu dès le premier jour pour répondre aux normes internationales les plus strictes en matière de sécurité, confidentialité et IA.",
  "iso.byDesign": "✔ Architecture par Conception",
  "gpu.badge": "CALCUL ET PERSISTANCE",
  "gpu.title": "Inférence GPU Locale &",
  "gpu.titleAccent": "Adhésion Cloud",
  "gpu.subtitle": "Aucun paywall logiciel. Le calcul s'exécute localement dès que le matériel est disponible.",
  "dao.badge": "FEUILLE DE ROUTE DE GOUVERNANCE",
  "dao.title": "Gouvernance Décentralisée &",
  "dao.titleAccent": "Transfert Communautaire",
  "dao.subtitle": "Fondé par Brahyan Belalcázar comme laboratoire communautaire. La gouvernance sera transférée à la DAO de la communauté.",
  "terminal.badge": "TERMINAL HUD INTERACTIF",
  "terminal.title": "> SIMULATEUR_CLI_SWAL",
  "terminal.subtitle": "Testez des commandes simulées en direct contre le noyau de mémoire Xavier et le réseau edge-mesh.",
  "terminal.placeholder": "Tapez une commande (ex: swal node status, xavier memory query, help)...",
  "terminal.execute": "Exécuter",
  "footer.desc": "SouthWest AI Labs (SWAL) est un laboratoire de recherche communautaire créé pour autonomiser l'humanité en préservant et décentralisant le savoir collectif.",
  "footer.founder": "Fondateur & Créateur: Brahyan Belalcázar (@iberi22 / \"ElBeRi\")",
  "footer.copyright": "© 2026 SouthWest AI Labs (SWAL). Open Source AGPL-3.0 / MIT.",
  "footer.linksTitle": "Liens de l'Écosystème",
  "footer.securityTitle": "Sécurité & Normes"
})

bn = create_locale("bn", "Bengali", {
  "nav.cores": "মূল স্তম্ভ",
  "nav.apps": "ইকোসিস্টেম (১৮টি অ্যাপ)",
  "nav.enterprise": "এন্টারপ্রাইজ",
  "nav.iso": "আইএসও মানদণ্ড",
  "nav.gpuCloud": "জিপিইউ ও ক্লাউড",
  "nav.dao": "ডিএও ও শাসন",
  "nav.launchNode": "নোড চালু করুন",
  "nav.networkVersion": "নেটওয়ার্ক v1.0",
  "theme.dark": "ডার্ক মোড",
  "theme.light": "লাইট মোড",
  "theme.auto": "সিস্টেম থিম",
  "hero.badge": "SWAL কমিউনিটি রিসার্চ ল্যাব ২০২৬",
  "hero.partners": "BELA কলম্বিয়া এবং ওপেন মেশ",
  "hero.title1": "বিকেন্দ্রীভূত স্মৃতি এবং",
  "hero.titleGradient": "সার্বভৌম মানব এআই",
  "hero.title2": "নেটওয়ার্ক।",
  "hero.subtitle": "মানবজাতির যৌথ জ্ঞানকে ১০০% নির্ধারণী ব্যবস্থাপনা এবং Xavier-এর মাধ্যমে অপরিবর্তনীয় P2P বিকেন্দ্রীকরণের দ্বারা রক্ষা করতে তৈরি একটি ল্যাব।",
  "hero.exploreApps": "ইকোসিস্টেম অন্বেষণ করুন (১৮টি অ্যাপ)",
  "hero.enterpriseCase": "এন্টারপ্রাইজ পোর্টাল",
  "hero.telemetryTitle": "নেটওয়ার্ক টেলিমেট্রি",
  "hero.telemetrySimulated": "[ সিমুলেটেড ডেটা / বেঞ্চমার্ক ]",
  "hero.statNodes": "লক্ষ্য ডিএও নোড",
  "hero.statSync": "CRDT P2P সিঙ্ক",
  "hero.statIso": "সিকিউরিটি রেডি",
  "cores.badge": "ক্যানোনিকাল আর্কিটেকচার",
  "cores.title": "৪টি একীভূত",
  "cores.titleAccent": "মূল স্তম্ভ",
  "cores.subtitle": "SWAL নেটওয়ার্কের প্রতিটি অ্যাপ্লিকেশনকে চালিত করার মূল অবকাঠামো।",
  "cores.inspectSource": "সোর্স কোড দেখুন",
  "apps.badge": "ক্যানোনিকাল পোর্টফোলিও",
  "apps.title": "SWAL ইকোসিস্টেম",
  "apps.titleCount": "(১৮টি অ্যাপ)",
  "apps.subtitle": "সমস্ত লাইভ এবং সক্রিয় বিকেন্দ্রীভূত অ্যাপ্লিকেশন অন্বেষণ করুন। কোনো সাবস্ক্রিপশন ছাড়াই প্রো সুবিধা অন্তর্ভুক্ত।",
  "apps.searchPlaceholder": "অ্যাপস, স্ট্যাক, ডোমেন খুঁজুন...",
  "apps.allProjects": "সমস্ত প্রজেক্ট (১৮)",
  "apps.catEnterprise": "শিল্প ও এন্টারপ্রাইজ",
  "apps.catCore": "মূল অবকাঠামো",
  "apps.catCivic": "নাগরিক ও শিক্ষা",
  "apps.catMobile": "মোবাইল ও পরিধানযোগ্য",
  "apps.catCreator": "এআই ও ক্রিয়েটর টুলস",
  "apps.liveDemo": "লাইভ ডেমো ↗",
  "apps.publicRepo": "রেপোজিটরি ↗",
  "apps.inviteOnly": "🔒 শুধুমাত্র আমন্ত্রণে",
  "apps.requestAccess": "অ্যাক্সেস অনুরোধ করুন",
  "status.production": "প্রোডাকশন",
  "status.active": "সক্রিয়",
  "status.beta": "বিটা",
  "status.published": "প্রকাশিত",
  "iso.badge": "মানদণ্ড ও সাইবার নিরাপত্তা",
  "iso.title": "আইএসও সম্মতি ও",
  "iso.titleAccent": "ডেটা গভর্নেন্স",
  "gpu.badge": "কম্পিউট ও স্থায়িত্ব",
  "gpu.title": "লোকাল জিপিইউ ইনফারেন্স ও",
  "gpu.titleAccent": "ক্লাউড মেম্বারশিপ",
  "dao.badge": "শাসন রোডম্যাপ",
  "dao.title": "বিকেন্দ্রীভূত শাসন ও",
  "dao.titleAccent": "কমিউনিটি হস্তান্তর",
  "terminal.badge": "ইন্টারেক্টিভ HUD টার্মিনাল",
  "terminal.title": "> SWAL_CLI_সিমুলেটর",
  "terminal.subtitle": "Xavier মেমরি কোর এবং মেশ নেটওয়ার্কের বিরুদ্ধে সিমুলেটেড কমান্ড পরীক্ষা করুন।",
  "terminal.placeholder": "একটি কমান্ড লিখুন (যেমন swal node status, xavier memory query, help)...",
  "terminal.execute": "রান করুন",
  "footer.desc": "SouthWest AI Labs (SWAL) মানবজাতির জ্ঞানকে রক্ষা ও বিকেন্দ্রীকরণ করার জন্য একটি মুক্ত গভীর-প্রযুক্তি গবেষণা ল্যাব।",
  "footer.founder": "প্রতিষ্ঠাতা ও স্রষ্টা: Brahyan Belalcázar (@iberi22 / \"ElBeRi\")",
  "footer.copyright": "© ২০২৬ SouthWest AI Labs (SWAL)। ওপেন সোর্স AGPL-3.0 / MIT।",
  "footer.linksTitle": "ইকোসিস্টেম লিঙ্ক",
  "footer.securityTitle": "নিরাপত্তা ও মানদণ্ড"
})

pt = create_locale("pt", "Portuguese", {
  "nav.cores": "Pilares Centrais",
  "nav.apps": "Ecossistema (18 Apps)",
  "nav.enterprise": "Empresarial",
  "nav.iso": "Normas ISO",
  "nav.gpuCloud": "GPU e Nuvem",
  "nav.dao": "DAO e Governança",
  "nav.launchNode": "Iniciar Nó",
  "nav.networkVersion": "Rede v1.0",
  "theme.dark": "Modo Escuro",
  "theme.light": "Modo Claro",
  "theme.auto": "Tema do Sistema",
  "hero.badge": "LABORATÓRIO DE PESQUISA SWAL 2026",
  "hero.partners": "BELA Colômbia & Rede Aberta",
  "hero.title1": "Memória Descentralizada e",
  "hero.titleGradient": "IA Humana Soberana",
  "hero.title2": "Rede.",
  "hero.subtitle": "Um laboratório comunitário criado para capacitar a humanidade, concentrando, preservando, refinando e protegendo o conhecimento coletivo humano com gestão 100% determinística e descentralização P2P via Xavier.",
  "hero.exploreApps": "Explorar Ecossistema (18 Apps)",
  "hero.enterpriseCase": "Portal Empresarial",
  "hero.telemetryTitle": "Telemetria de Rede",
  "hero.telemetrySimulated": "[ Dados Simulados / Benchmark ]",
  "hero.statNodes": "Nós Meta DAO",
  "hero.statSync": "Sincronização CRDT P2P",
  "hero.statIso": "Segurança Pronta ISO",
  "cores.badge": "ARQUITETURA CANÔNICA",
  "cores.title": "Os 4 Pilares",
  "cores.titleAccent": "Unificados",
  "cores.subtitle": "A infraestrutura fundamental que alimenta todas as aplicações na rede SWAL. Zero silos proprietários, 100% código soberano determinístico.",
  "cores.inspectSource": "Inspecionar Código",
  "apps.badge": "PORTFÓLIO CANÔNICO",
  "apps.title": "Ecossistema SWAL",
  "apps.titleCount": "(18 Apps)",
  "apps.subtitle": "Explore todas as aplicações descentralizadas ativas. Cada app inclui recursos Pro completos sem assinaturas.",
  "apps.searchPlaceholder": "Buscar apps, stack, domínio...",
  "apps.allProjects": "Todos os Projetos (18)",
  "apps.catEnterprise": "Industrial e Empresarial",
  "apps.catCore": "Infraestrutura Central",
  "apps.catCivic": "Cívico e Educação",
  "apps.catMobile": "Mobile e Wearables",
  "apps.catCreator": "Ferramentas de IA e Criadores",
  "apps.liveDemo": "Demo ao Vivo ↗",
  "apps.publicRepo": "Repositório ↗",
  "apps.inviteOnly": "🔒 Apenas Convite",
  "apps.requestAccess": "Solicitar Acesso",
  "status.production": "Produção",
  "status.active": "Ativo",
  "status.beta": "Beta",
  "status.published": "Publicado",
  "iso.badge": "NORMAS E CIBERSEGURANÇA",
  "iso.title": "Conformidade ISO e",
  "iso.titleAccent": "Governança de Dados",
  "iso.subtitle": "Projetado desde o primeiro dia para satisfazer rigorosos padrões internacionais de segurança e privacidade.",
  "iso.byDesign": "✔ Arquitetura por Design",
  "gpu.badge": "COMPUTAÇÃO E PERSISTÊNCIA",
  "gpu.title": "Inferência Local por GPU e",
  "gpu.titleAccent": "Membro Cloud",
  "gpu.subtitle": "Sem paywalls de software. A computação roda localmente quando há hardware disponível.",
  "dao.badge": "RODAPÉ DE GOVERNANÇA",
  "dao.title": "Governança Descentralizada e",
  "dao.titleAccent": "Transferência Comunitária",
  "dao.subtitle": "Fundado por Brahyan Belalcázar como laboratório comunitário. A governança total será transferida para a DAO.",
  "terminal.badge": "TERMINAL HUD INTERATIVO",
  "terminal.title": "> SIMULADOR_SWAL_CLI",
  "terminal.subtitle": "Testar comandos simulados ao vivo contra o núcleo de memória Xavier e a rede edge-mesh.",
  "terminal.placeholder": "Digite um comando (ex: swal node status, xavier memory query, help)...",
  "terminal.execute": "Executar",
  "footer.desc": "SouthWest AI Labs (SWAL) é um laboratório comunitário de pesquisa criado para capacitar a humanidade preservando e descentralizando o conhecimento.",
  "footer.founder": "Fundador e Criador: Brahyan Belalcázar (@iberi22 / \"ElBeRi\")",
  "footer.copyright": "© 2026 SouthWest AI Labs (SWAL). Código Aberto AGPL-3.0 / MIT.",
  "footer.linksTitle": "Links do Ecossistema",
  "footer.securityTitle": "Segurança e Padrões"
})

ru = create_locale("ru", "Russian", {
  "nav.cores": "Основные Задачи",
  "nav.apps": "Экосистема (18 Приложений)",
  "nav.enterprise": "Предприятиям",
  "nav.iso": "Стандарты ISO",
  "nav.gpuCloud": "GPU и Облако",
  "nav.dao": "DAO и Управление",
  "nav.launchNode": "Запустить Узел",
  "nav.networkVersion": "Сеть v1.0",
  "theme.dark": "Тёмная Тема",
  "theme.light": "Светлая Тема",
  "theme.auto": "Системная Тема",
  "hero.badge": "ИССЛЕДОВАТЕЛЬСКАЯ ЛАБОРАТОРИЯ SWAL 2026",
  "hero.partners": "BELA Колумбия и Открытая Сеть",
  "hero.title1": "Децентрализованная Память и",
  "hero.titleGradient": "Суверенный ИИ Человечества",
  "hero.title2": "Сеть.",
  "hero.subtitle": "Общественная лаборатория, созданная для расширения возможностей человечества путем сохранения, совершенствования и защиты коллективных знаний с помощью 100% детерминированного управления и P2P децентрализации через Xavier.",
  "hero.exploreApps": "Исследовать Экосистему (18 Приложений)",
  "hero.enterpriseCase": "Портал Предприятия",
  "hero.telemetryTitle": "Телеметрия Сети",
  "hero.telemetrySimulated": "[ Симулированные Данные / Бенчмарк ]",
  "hero.statNodes": "Целевые Узлы DAO",
  "hero.statSync": "Синхронизация CRDT P2P",
  "hero.statIso": "Безопасность ISO",
  "cores.badge": "КАНОНИЧЕСКАЯ АРХИТЕКТУРА",
  "cores.title": "4 Единых",
  "cores.titleAccent": "Ключевых Столпа",
  "cores.subtitle": "Базовая инфраструктура, обеспечивающая работу каждого приложения в сети SWAL. Ноль проприетарных ограничений, 100% суверенный код.",
  "cores.inspectSource": "Исходный Код",
  "apps.badge": "КАНОНИЧЕСКИЙ ПОРТФЕЛЬ",
  "apps.title": "Экосистема SWAL",
  "apps.titleCount": "(18 Приложений)",
  "apps.subtitle": "Исследуйте все децентрализованные приложения. Каждое приложение включает полные возможности Pro без подписок.",
  "apps.searchPlaceholder": "Поиск приложений, стека, домена...",
  "apps.allProjects": "Все Проекты (18)",
  "apps.catEnterprise": "Промышленность и Бизнес",
  "apps.catCore": "Базовая Инфраструктура",
  "apps.catCivic": "Образование и Общество",
  "apps.catMobile": "Мобильные и Устройства",
  "apps.catCreator": "Инструменты ИИ и Авторов",
  "apps.liveDemo": "Демо Онлайн ↗",
  "apps.publicRepo": "Репозиторий ↗",
  "apps.inviteOnly": "🔒 По Приглашению",
  "apps.requestAccess": "Запросить Доступ",
  "status.production": "Продакшн",
  "status.active": "Активен",
  "status.beta": "Бета",
  "status.published": "Опубликован",
  "iso.badge": "СТАНДАРТЫ И КИБЕРБЕЗОПАСНОСТЬ",
  "iso.title": "Соответствие ISO и",
  "iso.titleAccent": "Управление Данными",
  "iso.subtitle": "Разработано с первого дня для удовлетворения строгих международных стандартов безопасности и конфиденциальности.",
  "iso.byDesign": "✔ Архитектура по Проекту",
  "gpu.badge": "ВЫЧИСЛЕНИЯ И ХРАНЕНИЕ",
  "gpu.title": "Локальный Вывод на GPU и",
  "gpu.titleAccent": "Облачное Членство",
  "gpu.subtitle": "Без платных барьеров. Вычисления выполняются локально при наличии оборудования.",
  "dao.badge": "ДОРОЖНАЯ КАРТА УПРАВЛЕНИЯ",
  "dao.title": "Децентрализованное Управление и",
  "dao.titleAccent": "Передача Сообществу",
  "dao.subtitle": "Основана Брайаном Белалькасаром как лаборатория. Управление протоколом будет передано в сообщество DAO.",
  "terminal.badge": "ИНТЕРАКТИВНЫЙ ТЕРМИНАЛ HUD",
  "terminal.title": "> СИМУЛЯТОР_SWAL_CLI",
  "terminal.subtitle": "Тестирование симулированных команд в ядре памяти Xavier и сети edge-mesh.",
  "terminal.placeholder": "Введите команду (например swal node status, xavier memory query, help)...",
  "terminal.execute": "Выполнить",
  "footer.desc": "SouthWest AI Labs (SWAL) — открытая исследовательская лаборатория deep-tech, созданная для децентрализации человеческих знаний.",
  "footer.founder": "Основатель и Создатель: Brahyan Belalcázar (@iberi22 / \"ElBeRi\")",
  "footer.copyright": "© 2026 SouthWest AI Labs (SWAL). Open Source AGPL-3.0 / MIT.",
  "footer.linksTitle": "Ссылки Экосистемы",
  "footer.securityTitle": "Безопасность и Стандарты"
})

ur = create_locale("ur", "Urdu", {
  "nav.cores": "بنیادی ستون",
  "nav.apps": "ایکوسسٹم (18 ایپس)",
  "nav.enterprise": "انٹرپرائز",
  "nav.iso": "ISO معیار",
  "nav.gpuCloud": "GPU اور کلاؤڈ",
  "nav.dao": "DAO اور گورننس",
  "nav.launchNode": "نوڈ شروع کریں",
  "nav.networkVersion": "نیٹ ورک v1.0",
  "theme.dark": "ڈارک موڈ",
  "theme.light": "لائٹ موڈ",
  "theme.auto": "سسٹم تھیم",
  "hero.badge": "SWAL کمیونٹی ریسرچ لیب 2026",
  "hero.partners": "BELA کولمبیا اور اوپن میش",
  "hero.title1": "غیر مرکز شدہ یادداشت اور",
  "hero.titleGradient": "خود مختار انسانی AI",
  "hero.title2": "نیٹ ورک۔",
  "hero.subtitle": "Xavier کے ذریعے 100% حتمی انتظام کے ساتھ انسانی اجتماعی علم کو محفوظ اور خودمختار بنانے کے لیے بنائی گئی لیب۔",
  "hero.exploreApps": "ایکوسسٹم دیکھیں (18 ایپس)",
  "hero.enterpriseCase": "انٹرپرائز پورٹل",
  "hero.telemetryTitle": "نیٹ ورک ٹیلی میٹری",
  "hero.telemetrySimulated": "[ سمیولیٹڈ ڈیٹا / بینچمارک ]",
  "hero.statNodes": "ٹارگٹ DAO نوڈس",
  "hero.statSync": "CRDT P2P سنک",
  "hero.statIso": "سیکیورٹی تیار",
  "cores.badge": "مستند فن تعمیر",
  "cores.title": "4 متحد",
  "cores.titleAccent": "بنیادی ستون",
  "cores.subtitle": "SWAL نیٹ ورک کی ہر ایپ کو طاقت دینے والا بنیادی ڈھانچہ۔ 100% خودمختار کوڈ۔",
  "cores.inspectSource": "سورس کوڈ دیکھیں",
  "apps.badge": "مستند پورٹ فولیو",
  "apps.title": "SWAL ایکوسسٹم",
  "apps.titleCount": "(18 ایپس)",
  "apps.subtitle": "تمام لائیو اور فعال غیر مرکز شدہ ایپلی کیشنز کا جائزہ لیں۔ بغیر کسی سبسکرپشن کے پرو خصوصیات شامل ہیں۔",
  "apps.searchPlaceholder": "ایپس، اسٹیک، ڈومین تلاش کریں...",
  "apps.allProjects": "تمام پروجیکٹس (18)",
  "apps.catEnterprise": "صنعتی اور انٹرپرائز",
  "apps.catCore": "بنیادی ڈھانچہ",
  "apps.catCivic": "شہریت اور تعلیم",
  "apps.catMobile": "موبائل اور پہننے کے قابل",
  "apps.catCreator": "AI اور تخلیق کار ٹولز",
  "apps.liveDemo": "لائیو ڈیمو ↗",
  "apps.publicRepo": "ریپوزٹری ↗",
  "apps.inviteOnly": "🔒 صرف دعوت نامہ",
  "apps.requestAccess": "رسائی کی درخواست کریں",
  "status.production": "پروڈکشن",
  "status.active": "فعال",
  "status.beta": "بیٹا",
  "status.published": "شائع شدہ",
  "iso.badge": "معیارات اور سائبر سیکیورٹی",
  "iso.title": "ISO کی تعمیل اور",
  "iso.titleAccent": "ڈیٹا گورننس",
  "gpu.badge": "کمپیوٹنگ اور استقامت",
  "gpu.title": "مقامی GPU کے نتائج اور",
  "gpu.titleAccent": "کلاؤڈ ممبرشپ",
  "dao.badge": "گورننس روڈ میپ",
  "dao.title": "غیر مرکز شدہ گورننس اور",
  "dao.titleAccent": "کمیونٹی کی تحویل",
  "terminal.badge": "انٹرایکٹو HUD ٹرمینل",
  "terminal.title": "> SWAL_CLI_سمیولیٹر",
  "terminal.subtitle": "Xavier میموری کور اور میش نیٹ ورک کے خلاف کمانڈز کی جانچ کریں۔",
  "terminal.placeholder": "ایک کمانڈ ٹائپ کریں (مثلاً swal node status, xavier memory query, help)...",
  "terminal.execute": "چلائیں",
  "footer.desc": "SouthWest AI Labs (SWAL) انسانی علم کو محفوظ اور غیر مرکز کرنے کے لیے ایک اوپن ریسرچ لیب ہے۔",
  "footer.founder": "بانی اور تخلیق کار: Brahyan Belalcázar (@iberi22 / \"ElBeRi\")",
  "footer.copyright": "© 2026 SouthWest AI Labs (SWAL)۔ اوپن سورس AGPL-3.0 / MIT۔",
  "footer.linksTitle": "ایکوسسٹم لنکس",
  "footer.securityTitle": "سیکیورٹی اور معیارات"
})

all_translations = {
    "en": en,
    "es": es,
    "zh": zh,
    "hi": hi,
    "ar": ar,
    "bn": bn,
    "pt": pt,
    "ru": ru,
    "ur": ur,
    "fr": fr
}

out = "export const TRANSLATIONS: Record<string, Record<string, string>> = {\n"
for lang_code, dict_data in all_translations.items():
    out += f'  "{lang_code}": ' + json.dumps(dict_data, ensure_ascii=False, indent=4) + ",\n"
out += "};\n\n"

out += """export type SupportedLanguage = "en" | "es" | "zh" | "hi" | "ar" | "bn" | "pt" | "ru" | "ur" | "fr";

export const LANGUAGE_OPTIONS: { code: SupportedLanguage; label: string; native: string; dir: "ltr" | "rtl" }[] = [
  { code: "en", label: "English", native: "English", dir: "ltr" },
  { code: "es", label: "Español", native: "Español", dir: "ltr" },
  { code: "zh", label: "Chinese", native: "中文", dir: "ltr" },
  { code: "hi", label: "Hindi", native: "हिन्दी", dir: "ltr" },
  { code: "ar", label: "Arabic", native: "العربية", dir: "rtl" },
  { code: "bn", label: "Bengali", native: "বাংলা", dir: "ltr" },
  { code: "pt", label: "Portuguese", native: "Português", dir: "ltr" },
  { code: "ru", label: "Russian", native: "Русский", dir: "ltr" },
  { code: "ur", label: "Urdu", native: "اردو", dir: "rtl" },
  { code: "fr", label: "French", native: "Français", dir: "ltr" }
];
"""

with open("src/i18n/translations.ts", "w", encoding="utf-8") as f:
    f.write(out)

print("translations.ts generated successfully!")
